### ISSUE TITLE
Mention code contribution and a potential bug fix. 

### ISSUE THREAD

**Issue by wwang2** [aksub99/molecular-vae#31]
Hi 

want to point out that this repo should cite the original code contribution from topazape/molecular-VAE and also cxhernandez/molencoder so that their contributions are clearly stated because what you did is essentially just reusing their code. I think this project is better started as a fork as supposed to a fresh repo.  

I have also fixed a bug on conv1d layer that existed in topazape/molecular-VAE that is also carried over to this repo, you can check it out here: https://github.com/topazape/molecular-VAE/issues/2.  That should also help you with further minimizing the loss.

**Comment by aksub99** [comment]
Hi,

Thanks for pointing this out @wwang2. I had lost track of this repo's origin since I had created it a couple of years ago. It indeed would have been better off being a fork since I have reused a good portion of topazape/molecular-VAE. I'll add a line to the `README` citing the original repo and directing future users there.

And thanks for letting me know about the bug fix! That's a great find.

**Comment by aksub99** [comment]
@wwang2 I wasn't aware of the cxhernandez/molencoder repository. Since I haven't directly re-used any code from there, do you still think it should be cited?

But I do recall that I had used code from https://github.com/maxhodak/keras-molecules to preprocess the dataset. So, will add in a citation to keras-molecules as well.

**Comment by wwang2** [comment]
Thanks @aksub99 . That was just my a suggestion, but thanks for considering it!

topazape/molecular-VAE is built from cxhernandez/molencoder according to the README.
